PUT http://localhost:8080/movies
Content-Type: application/json

{
	"title": "花木兰",
	"released": 2020,
	"description": "测试创建 Movie 节点",
	"actorsAndRoles": {
		"刘亦菲": [
			"花木兰"
		]
	},
	"directors": [
		{
			"name": "徐峥"
		}
	]
}

###

GET http://localhost:8080/movies
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/movies/by-title?title=Aeon Flux
Accept: */*
Cache-Control: no-cache

###

DELETE http://localhost:8080/movies/The Matrix Reloaded
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/movies/all
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/movies/37
Accept: */*
Cache-Control: no-cache

###


GET http://localhost:8080/movies/all-by-title?title=chendaye666
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/movies/client?title=111
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/persons/getPersonsWhoActAndDirect
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8080/persons/20
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/persons/setBorn
Content-Type: application/json

{
  "id": 23,
  "born": 3033
}

###
